version: '3.8'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: untitled
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: untitled
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  untitled:
    build: .
    depends_on:
      - mongodb
    environment:
      MONGO_URL: "mongodb://untitled:password@mongodb:27017/untitled"
    ports:
      - "8080:8080"

volumes:
  mongodb_data: