version: '3.8'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: untitled
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: untitled
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
