application:
  title: "Untitled"
  banner:
    title: "banner"
    content: "Some banner"

server:
  address: 0.0.0.0
  port: 8080
  compression:
    enabled: true
  http2:
    enabled: true
  netty:
    connection-timeout: 1000ms
    validate-headers: true
  error:
    include-binding-errors: always
  forward-headers-strategy: framework

spring:
  main:
    banner-mode: off
    cloud-platform: kubernetes
    log-startup-info: on
    web-application-type: reactive
  codec:
    log-request-details: true
  cache:
    type: simple
  jackson:
    locale: en_US
    property-naming-strategy: SNAKE_CASE
mongodb:
    uri: mongodb://localhost:27017




springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /api-docs/swagger-ui.html
    enabled: true

logging:
  level:
    web: debug
  charset:
    console: UTF-8
    file: UTF-8
trace: false
debug: true
